export let products = [
	{name: 'Chicken Breast Fillets, Boneless Matuu maMarinated 6 Ounce Raw, Invivid',
	brand: 'Hormel Black LabeImany', 
	price: '$60.67/6*1LB',
	quantity: '0 X6*1LB', 
	total: '0',
	status: ''},
    {name: 'Chicken Breast Fillets, Boneless Matuu maMarinated 6 Ounce Raw, Invivid',
	brand: 'Hormel Black LabeImany', 
	price: '$60.67/6*1LB',
	quantity: '0 X6*1LB', 
	total: '0',
	status: ''},
    {name: 'Chicken Breast Fillets, Boneless Matuu maMarinated 6 Ounce Raw, Invivid',
	brand: 'Hormel Black LabeImany', 
	price: '$60.67/6*1LB',
	quantity: '0 X6*1LB', 
	total: '0',
	status: ''},
    {name: 'Chicken Breast Fillets, Boneless Matuu maMarinated 6 Ounce Raw, Invivid',
	brand: 'Hormel Black LabeImany', 
	price: '$60.67/6*1LB',
	quantity: '0 X6*1LB', 
	total: '0',
	status: ''},
    {name: 'Chicken Breast Fillets, Boneless Matuu maMarinated 6 Ounce Raw, Invivid',
	brand: 'Hormel Black LabeImany', 
	price: '$60.67/6*1LB',
	quantity: '0 X6*1LB', 
	total: '0',
	status: ''},
    {name: 'Chicken Breast Fillets, Boneless Matuu maMarinated 6 Ounce Raw, Invivid',
	brand: 'Hormel Black LabeImany', 
	price: '$60.67/6*1LB',
	quantity: '0 X6*1LB', 
	total: '0',
	status: ''},


]